services:
# =====================================================================================
# ENV DEV
# =====================================================================================

  project-service-dev:
    image: project-service-dev
    container_name: project-service-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run start:dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@project-db-dev:5432/project-db
    env_file:
      - ./src/infrastructure/config/.env.dev
    depends_on:
      - project-db-dev
    profiles: ["dev"]

  project-db-dev:
    image: postgres:16
    container_name: project-db-dev
    env_file:
      - ./src/infrastructure/config/.env.dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    profiles: ["dev"]


# =====================================================================================
# ENV PROD
# =====================================================================================

  project-service-prod:
    container_name: project-service-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - ./src/infrastructure/config/.env.prod
    depends_on:
      - project-db-prod
    restart: unless-stopped
    profiles: ["prod"]

  project-db-prod:
    image: postgres:16
    container_name: project-db-prod
    env_file:
      - ./src/infrastructure/config/.env.prod
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
    restart: unless-stopped
    profiles: ["prod"]

volumes:
  pgdata-dev:
  pgdata-prod:
