FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY src/infrastructure/config/.env.dev .env
ENV PRISMA_CLIENT_ENGINE_TYPE=binary
ENV PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1

COPY . .
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]