export const CodesError = {
  PUBLIC_ID_INVALID: "PUBLIC_ID_INVALID",
  PAGE_INVALID: "PAGE_INVALID",
  LIMIT_INVALID: "LIMIT_INVALID",

  PROJECT_ID_INVALID: "PROJECT_ID_INVALID",
  PROJECT_TITLE_REQUIRED: "PROJECT_TITLE_REQUIRED",
  PROJECT_DESCRIPTION_REQUIRED: "PROJECT_DESCRIPTION_REQUIRED",
  PROJECT_GITHUB_URL_INVALID: "PROJECT_GITHUB_URL_INVALID",
  PROJECT_ADDRESS_URL_INVALID: "PROJECT_ADDRESS_URL_INVALID",
  PROJECT_IS_PUBLIC_INVALID: "PROJECT_IS_PUBLIC_INVALID",
  PROJECT_TECHNOLOGIES_ID_INVALID: "PROJECT_TECHNOLOGIES_ID_INVALID",

  TECHNOLOGY_ID_INVALID: "TECHNOLOGY_ID_INVALID",
  TECHNOLOGY_ARCHITECTURE_ID_INVALID: "TECHNOLOGY_ARCHITECTURE_ID_INVALID",
  TECHNOLOGY_FRAMEWORK_ID_INVALID: "TECHNOLOGY_FRAMEWORK_ID_INVALID",
  TECHNOLOGY_UTILS_GESTION_ID_INVALID: "TECHNOLOGY_UTILS_GESTION_ID_INVALID",

  TAG_ID_INVALID: "TAG_ID_INVALID",
  TAG_NAME_REQUIRED: "TAG_NAME_REQUIRED",
  TAG_DESCRIPTION_REQUIRED: "TAG_DESCRIPTION_REQUIRED",

  PROJECT_TAG_ID_INVALID: "PROJECT_TAG_ID_INVALID",
  PROJECT_TAG_PROJECT_ID_INVALID: "PROJECT_TAG_PROJECT_ID_INVALID",
  PROJECT_TAG_TAG_ID_INVALID: "PROJECT_TAG_TAG_ID_INVALID",
} as const;

export type CodesError = (typeof CodesError)[keyof typeof CodesError];
