export const CodesError = {
  DATA_INVALID: "DATA_INVALID",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  TECHNOLOGY_NOT_FOUND: "TECHNOLOGY_NOT_FOUND",
  TAG_NOT_FOUND: "TAG_NOT_FOUND",
  PROJECT_TAG_NOT_FOUND: "PROJECT_TAG_NOT_FOUND",
  DUPLICATE_PROJECT: "DUPLICATE_PROJECT",
  DUPLICATE_TECHNOLOGY: "DUPLICATE_TECHNOLOGY",
  DUPLICATE_TAG: "DUPLICATE_TAG",
  DUPLICATE_PROJECT_TAG: "DUPLICATE_PROJECT_TAG",
} as const;

export type CodesError = (typeof CodesError)[keyof typeof CodesError];
